builds:
  - binary: terraform-provider-linuxkit_v{{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  - format: zip
