dist: trusty
sudo: required

language: go
go:
  - "1.11"

stages:
  - test
  - release

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg'
    packages:
      - bazel

jobs:
  include:
    - stage: test
      script: make test
    - stage: release
      script: make release
      deploy:
        provider: releases
        api_key:
          secure: "TODO"
        file: release.tar.gz
        skip_cleanup: true
        on:
          tags: true

