[prune]
  go-tests = true
  unused-packages = true
  non-go = true
  
[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.8"

[[override]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[override]]
  name = "github.com/docker/docker"
  revision = "ba99c19b593bdb9e7b90793681fe89b0a91781ed"